apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: my-gateway
spec:
  observability:
    metrics:
      prometheus:
        enabled: true
        annotations:
          enabled: true
