apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: t24-data-retrieval-mapping
spec:
  gatewayRef:
    name: my-gateway
  routeConfigRef:
    name: t24-data-retrieval-route-config
