apiVersion: apps/v1
kind: Deployment
metadata:
  name: ztb-front-app-deployment
spec:
  selector:
    matchLabels:
      app: ztb-front-app
  replicas: 2
  template:
    metadata:
      labels:
        app: ztb-front-app
    spec:
      containers:
      - name: ztb-front-app
        image: "{{ .Values.image.container }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: ztb-front-app-pvc
